language: objective-c 
cache: cocoapods
osx_image: xcode8.2

script:
 - gem install cocoapods --pre
 - pod repo update 

xcode_workspace: Pickery.xcworkspace
xcode_scheme: iOS
xcode_sdk: iphonesimulator8.4
