language: objective-c 
cache: cocoapods
osx_image: xcode8.2

before_install:
 - pod repo update 

xcode_workspace: Pickery.xcworkspace
xcode_scheme: iOS

script: xcodebuild -scheme "iOS" -workspace "Pickery.xcworkspace" -sdk iphonesimulator | xcpretty && exit ${PIPESTATUS[0]}